apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
  labels:
    environment: stable
spec:
  dependsOn:
    - name: flux-system
  interval: 10m
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/cloudnative-pg

  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: pg-core-stable
      namespace: postgres

  patches:
    - target:
        kind: Job
        name: bootstrap-app-privs
        namespace: postgres
      patch: |-
        - op: add
          path: /metadata/labels/environment
          value: stable
        - op: add
          path: /spec/template/metadata/labels/environment
          value: stable
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: ENVIRONMENT
            value: "stable"
        - op: add
          path: /spec/template/spec/initContainers/0/env/-
          value:
            name: ENVIRONMENT
            value: "stable"



