apiVersion: v1
data:
  admin-password: cHJvbS1vcGVyYXRvcg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: rancher-monitoring
    meta.helm.sh/release-namespace: cattle-monitoring-system
  creationTimestamp: "2025-12-15T06:44:05Z"
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: rancher-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/version: 12.1.1
    chart: grafana-10.0.0
    helm.sh/chart: grafana-10.0.0
    heritage: Helm
    release: rancher-monitoring
  name: rancher-monitoring-grafana
  namespace: cattle-monitoring-system
  resourceVersion: "65949976"
  uid: 51ed9c3d-95f8-43b5-bb03-613a09a9c1fc
type: Opaque
