apiVersion: v1
kind: ConfigMap
metadata:
  name: default-privs-sql
data:
  default-privs.sql: |
    \set ON_ERROR_STOP 1
    -- variables: -v DB_NAME=... -v OWNER_ROLE=... -v APP_ROLE=...

    -- Create roles if missing
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'OWNER_ROLE') THEN
        EXECUTE format('CREATE ROLE %I LOGIN', :'OWNER_ROLE');
      END IF;
    END
    $$;

    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'APP_ROLE') THEN
        EXECUTE format('CREATE ROLE %I NOLOGIN', :'APP_ROLE');
      END IF;
    END
    $$;

    -- Make the app role owned by Vault's DB user so Vault can grant it
    \set vm 'vault_manager'
    SELECT format('ALTER ROLE %I OWNER TO %I', :'APP_ROLE', :'vm') \gexec

    -- Allow Vault's DB user to grant the app role
    SELECT format('GRANT %I TO %I WITH ADMIN OPTION', :'APP_ROLE', :'vm') \gexec

    -- Grant CONNECT at cluster level:
    SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'DB_NAME', :'APP_ROLE') \gexec

    -- Switch to target DB for schema/default-privileges work:
    \connect :DB_NAME

    -- Ensure schema exists (schema name == DB_NAME)
    SELECT format('CREATE SCHEMA IF NOT EXISTS %I', :'DB_NAME') \gexec

    -- USAGE on schema:
    SELECT format('GRANT USAGE ON SCHEMA %I TO %I', :'DB_NAME', :'APP_ROLE') \gexec

    -- Table/sequence privileges on existing objects:
    SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I', :'DB_NAME', :'APP_ROLE') \gexec
    SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I', :'DB_NAME', :'APP_ROLE') \gexec

    -- Default privileges for future objects created by OWNER_ROLE:
    SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I',
                  :'OWNER_ROLE', :'DB_NAME', :'APP_ROLE') \gexec
    SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO %I',
                  :'OWNER_ROLE', :'DB_NAME', :'APP_ROLE') \gexec

    -- Search path for OWNER_ROLE in this DB:
    \connect postgres
    SELECT format('ALTER ROLE %I IN DATABASE %I SET search_path = %I, public',
                  :'OWNER_ROLE', :'DB_NAME', :'DB_NAME') \gexec
