# Watches helm chart repositories for new versions
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts 
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 24h
  releaseName: cnpg-operator
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
      interval: 24h
  upgrade:
    crds: CreateReplace
