# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring-crd
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-monitoring-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: cattle-monitoring-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  dependsOn:
    - name: rancher-monitoring-crd
      namespace: cattle-monitoring-system
  chart:
    spec:
      chart: rancher-monitoring
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: cattle-monitoring-system
  values:
    global:
      cattle:
        clusterId: c-7rtn4
        clusterName: cluster01
        systemProjectId: p-ktssc
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          editable: true
          url: http://loki.cattle-logging-system.svc.cluster.local
    prometheus:
      prometheusSpec:
        retention: 5d
        retentionSize: 25GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 25Gi
    nameOverride: rancher-monitoring
    namespaceOverride: cattle-monitoring-system
    rke2IngressNginx:
      enabled: true
      namespaceOverride: kube-system
      service:
        selector:
          app.kubernetes.io/name: rke2-ingress-nginx
    rke2ControllerManager:
      enabled: false
    rke2Scheduler:
      enabled: false
    rke2Proxy:
      enabled: false
    rke2Etcd:
      enabled: false
