apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzMlUFz4jgThv9Ln20wBgPxLTXfTNVXlWSpzNZeUhzaUtuoIqu9cpsZNuX/viUDCQRSk73NTYh+W939PpJfoCZBjYKQv4DFgmwbVtg0o+euIO9IqB0ZHhvXCjpFkINHpzbkY8tVZVwVe2aB6IqmRocV6bjY/ReVwzqcUtqOnBRGoI/gsHctR/wWuI9rGxzKVChi6TW23bVCNUTAPxz5RyrJk1PUQv4U+jV/kW8NO8jhoBgV6P5Boyx3OtS1nRQkOIEIFDvxbC15yMV3FMGzcRpy+HYs5bYid6zn4947E0RznZTLm2kW41zN4pnOyng5K9MY9SRd3mQ3KaoE+nUfQduQCu60ZEkJ+7CuUdTm7jc1ro9AqG4sCg21nrCGzrGgGHZD3WpD6rnt6vFeHRdGRopdCTlMZtMUF/OElot5OknVYjpXxXJJWabSJFnQAtNFlmm8IVLpJJ1naZFNk+lsOsmKeZrMAj+/K9knpgao0DjyeyIV1zUGqJ7gZCbjwriTnxBBrCA6iyBRMTfkUdhfTHMdgamxOul1XBvv2ZM+3KP4TZJPR5PREg6SVWftiq1RoeX/lw8sK0/tGeZnhTXs5djKobMVe4E8TdLkVVKzM4HkCBrPwoot5PDnlxX06wg8tdz54Y6+gDW1kT0rTQc5pEkSbnNNNftQ0iRJ7oPVnv7uqD2NnLyLzEJgmDypzhvZfWEn9FMGOqzlHytvtsZSRV9bhXZgFPISbUsRKGywMNaI2VelPTfBo9u7O1gPp6P+w9ndI7N8M5YOr87wTPQRbNl2Nd1z5w6zqcNyhbKBHMZb9GNrirFm9Ux+fELE67y26K0pzv45Hnk85FpSrsbnObj6hPQDqt4yBaZMBRdCQWNjXbwFNtyaMEddXAYXXVme9Xjc6NcBgkuXBuv81ii6VSpkevjk10HYhg72b87TC1BZkhLI4YG/qw3pzhJE8EwBEseaYs+W3t3hw9sfNxZdiN6i7cLhYYBDbydJv/4k1cmvc5IofZFqfaRlX+uG28PEXqD5JS/9x8CEGj9MxtU7aeAkKM4NH1zxJPuPUVh9zoJ+GFDdyO5/xu+dvA7I1ZgTLvoIukaj0HfxKFTtQmDgQlC6/dXvvCcnD11dkD+6qyFPItDUGk/62l9u2Ls3bXtl+5FQ7yBP+v7fAAAA//9QSwcI2+Xx+2wDAAA3CQAAUEsBAhQAFAAIAAgAAAAAANvl8ftsAwAANwkAAAgAAAAAAAAAAAAAAAAAAAAAAG9yaWdpbmFsUEsFBgAAAAABAAEANgAAAKIDAAAAAA==
      deprecated.daemonset.template.generation: "1"
    creationTimestamp: "2025-12-15T08:23:33Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: rancher-logging-root
      app.kubernetes.io/managed-by: rancher-logging-root
      app.kubernetes.io/name: fluentbit
    name: rancher-logging-root-fluentbit
    namespace: cattle-logging-system
    ownerReferences:
    - apiVersion: logging.banzaicloud.io/v1beta1
      controller: true
      kind: FluentbitAgent
      name: rancher-logging-root
      uid: 6d0f8935-a6c4-4d5f-84f2-ad1289592ac0
    resourceVersion: "66004949"
    uid: 76d0f9cf-7a1d-4694-8cd0-d481d027a5db
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: rancher-logging-root
        app.kubernetes.io/managed-by: rancher-logging-root
        app.kubernetes.io/name: fluentbit
    template:
      metadata:
        annotations:
          checksum/fluent-bit.conf: 1432a760e876212c736cb88e55c2007e7a2755da9eec212652b53034315b6204
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: rancher-logging-root
          app.kubernetes.io/managed-by: rancher-logging-root
          app.kubernetes.io/name: fluentbit
      spec:
        containers:
        - command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc-operator/fluent-bit.conf
          image: rancher/mirrored-fluent-fluent-bit:3.1.8
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          ports:
          - containerPort: 2020
            name: monitor
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/docker/containers
            name: varlibcontainers
            readOnly: true
          - mountPath: /var/log/
            name: varlogs
            readOnly: true
          - mountPath: /fluent-bit/etc-operator
            name: config
          - mountPath: /tail-db
            name: positiondb
          - mountPath: /buffers
            name: buffers
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: rancher-logging-root-fluentbit
        serviceAccountName: rancher-logging-root-fluentbit
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          value: "true"
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          value: "true"
        volumes:
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibcontainers
        - hostPath:
            path: /var/log
            type: ""
          name: varlogs
        - name: config
          secret:
            defaultMode: 420
            secretName: rancher-logging-root-fluentbit
        - emptyDir: {}
          name: positiondb
        - emptyDir: {}
          name: buffers
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 3
    desiredNumberScheduled: 3
    numberAvailable: 3
    numberMisscheduled: 0
    numberReady: 3
    observedGeneration: 1
    updatedNumberScheduled: 3
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: rancher-logging
      meta.helm.sh/release-namespace: cattle-logging-system
    creationTimestamp: "2025-12-15T08:23:21Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: rancher-logging
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-logging
      app.kubernetes.io/version: 4.10.0
      helm.sh/chart: rancher-logging-108.0.0_up4.10.0-rancher.15
    name: rancher-logging
    namespace: cattle-logging-system
    resourceVersion: "66004771"
    uid: d512cbac-d50e-4e08-b7ed-092046d8fa9f
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: rancher-logging
        app.kubernetes.io/name: rancher-logging
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: rancher-logging
          app.kubernetes.io/name: rancher-logging
      spec:
        containers:
        - args:
          - -enable-leader-election=true
          image: rancher/mirrored-kube-logging-logging-operator:4.10.0
          imagePullPolicy: IfNotPresent
          name: rancher-logging
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
        serviceAccount: rancher-logging
        serviceAccountName: rancher-logging
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-12-15T08:23:26Z"
      lastUpdateTime: "2025-12-15T08:23:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-12-15T08:23:21Z"
      lastUpdateTime: "2025-12-15T08:23:26Z"
      message: ReplicaSet "rancher-logging-5d8cb755f5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzMVVFv2zYQ/i/3LNqSa6eNgD5kbbMNSFojafdSBMOJOtlEKJIjj069QP99oKTaTuNuWZ7yZJq678jvu++O99ASY42MUN6Dxop0SCt0bnIbK/KGmMJE2am0rbOGDEMJjY5kuIbsSFyLBldUi2oLJXg0ck1eaLtaKbMS3lo+ijLY0kHiLoNx51gGsT8/RQWHMoVKZNa0iwzbwNRCBvbOkL+ihjwZSQHKr4mf+oN8UNZACSNiUqH5G5XUNtbpTpuiIsYCMpDWsLdak4eSfaQMbpWpoYSLAQn/el3IIKoUfXoyw4VcnIp6dtqIeTNfiFO5eCXeIGG1wNdvinkO3U2XQXAkUxmcrS97PVsyvLRayaTqJ1+Tp/qKsN5CBoE0SbY+AVpkub54MWVMVMhvlKSP/11OsSasNYUAGTC1TiNTz+nAoWiMZWRlTc9vQFaK0+H0TepYp1NSjZKHXo6fD2qazITKkB+cSGbT/46IX76cn3+4+nN59vk3yGCDOqbdaRWbJiG6mwxUi6sDLaet8t56qkW6wu5q49HlppgUJ2I+KXLRRK1hxC+j1jtD/d58tLz0FJIcGWi1IUMhLL2t+gooo1ihfk8at9ckrakDlK/yDBx5ZevdVrHIgKW7tvKWePCvZyhn89k87/Y9vZc7fR9k2Kmy3EN+AAhlXEz3c96ylVZDCZ/fLaHLjsFfFTt4a41K/fEYeZOBp2Cj7+fCPWjVKu5X0kUoITV/S631SaV5nl8mV3n6K1I4DFvkeXsYWfSRvfll9Iq376xh+tZLglrbu6VXG6VpRR+CRN37GcoGdaAMJDqslFashjvV3joov8LZxQXc9Mdj/cno7ZW1fK40jXNugHcZbKyOLV3aaEZp27RcIq+TkUbtp8Ryuh9b0ppGrXolj0ajc2KM2WEO9n6KCyQ98R5jI7vIYtx+BPvu8idNfzFE9wPzHtCvElsQYuAvauXfHrKF7CffHnAT4o6qtbW3Inr9ds3syum0mL2e5JN8UpSz+Xw+n6JT0wEx8aQt1vDkrhxgYoCRLzcp78lTmvJBpXYJ4KGBX7TlnmuioXg/OPUm9e4Rrk341dvooCzyIgMfzdnjjS8hPeRFnu+fpzMp09FPeKXgO91wOLZ3vEZrl/fj6ikZu0T9aIc8K58YcjxI+0D75+RE54aE1Drevld+cNv/69Mug+hqZLpmj0yrbUqSisDIcXinN6g0VpquyGklMUCZJ//t/nTdPwEAAP//UEsHCH/dxCagAwAAswoAAFBLAQIUABQACAAIAAAAAAB/3cQmoAMAALMKAAAIAAAAAAAAAAAAAAAAAAAAAABvcmlnaW5hbFBLBQYAAAAAAQABADYAAADWAwAAAAA=
    creationTimestamp: "2025-12-15T08:23:32Z"
    generation: 1
    labels:
      app.kubernetes.io/component: fluentd
      app.kubernetes.io/managed-by: rancher-logging-root
      app.kubernetes.io/name: fluentd
    name: rancher-logging-root-fluentd
    namespace: cattle-logging-system
    ownerReferences:
    - apiVersion: logging.banzaicloud.io/v1beta1
      controller: true
      kind: Logging
      name: rancher-logging-root
      uid: 962a5c59-d29f-4f45-9c53-8aeab5a78140
    resourceVersion: "66004973"
    uid: bf0a0bad-0e33-4e32-93d5-1bb0730fe1f4
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: fluentd
        app.kubernetes.io/managed-by: rancher-logging-root
        app.kubernetes.io/name: fluentd
    serviceName: rancher-logging-root-fluentd-headless
    template:
      metadata:
        annotations:
          fluentbit.io/exclude: "true"
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: fluentd
          app.kubernetes.io/managed-by: rancher-logging-root
          app.kubernetes.io/name: fluentd
      spec:
        containers:
        - env:
          - name: BUFFER_PATH
            value: /buffers
          image: rancher/mirrored-kube-logging-fluentd:v1.16-4.10-full
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            tcpSocket:
              port: 24240
            timeoutSeconds: 1
          name: fluentd
          ports:
          - containerPort: 24240
            name: fluent-input
            protocol: TCP
          - containerPort: 24231
            name: monitor
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 400M
            requests:
              cpu: 500m
              memory: 100M
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /fluentd/etc/
            name: config
          - mountPath: /fluentd/app-config
            name: app-config
          - mountPath: /fluentd/secret
            name: output-secret
          - mountPath: /buffers
            name: rancher-logging-root-fluentd-buffer
        - args:
          - --volume-dir=/fluentd/etc
          - --volume-dir=/fluentd/app-config
          - --webhook-url=http://127.0.0.1:24444/api/config.reload
          image: rancher/mirrored-kube-logging-config-reloader:v0.0.6
          imagePullPolicy: IfNotPresent
          name: config-reloader
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /fluentd/app-config
            name: app-config
          - mountPath: /fluentd/etc
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 101
          runAsGroup: 101
          runAsUser: 100
        serviceAccount: rancher-logging-root-fluentd
        serviceAccountName: rancher-logging-root-fluentd
        terminationGracePeriodSeconds: 30
        volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: rancher-logging-root-fluentd
        - name: output-secret
          secret:
            defaultMode: 420
            secretName: rancher-logging-root-fluentd-output
        - name: app-config
          secret:
            defaultMode: 420
            secretName: rancher-logging-root-fluentd-app
        - emptyDir: {}
          name: rancher-logging-root-fluentd-buffer
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: rancher-logging-root-fluentd-69d4796744
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: rancher-logging-root-fluentd-69d4796744
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
