# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging-crd
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-logging-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: cattle-logging-system
  upgrade:
    cleanupOnFail: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
spec:
  interval: 24h
  dependsOn:
    - name: rancher-logging-crd
  chart:
    spec:
      chart: rancher-logging
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: cattle-logging-system
  values:
    logging:
      enabled: false
    additionalLoggingSources:
      rke2:
        enabled: true
    systemdLogPath: /var/log/journal
    disablePvc: true
    monitoring:
      serviceMonitor:
        enabled: false
    fluentbit:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      metrics:
        serviceMonitor: false
        prometheusRules: false
    fluentd:
      bufferStorageVolume:
        emptyDir:
          sizeLimit: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
      metrics:
        serviceMonitor: false
        prometheusRules: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 24h
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: cattle-logging-system
  values:
    global:
      dnsService: rke2-coredns-rke2-coredns
    loki:
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      schemaConfig:
        configs:
          - from: 2024-04-01
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 2
      storage:
        type: azure
        azure:
          # Name of the Azure Blob Storage account
          accountName: <your-account-name>
          # Key associated with the Azure Blob Storage account
          accountKey: <your-account-key>
          # Comprehensive connection string for Azure Blob Storage account (Can be used to replace endpoint, accountName, and accountKey)
          connectionString: <your-connection-string>
          # Flag indicating whether to use Azure Managed Identity for authentication
          useManagedIdentity: false
          # Flag indicating whether to use a federated token for authentication
          useFederatedToken: false
          # Client ID of the user-assigned managed identity (if applicable)
          userAssignedId: <your-user-assigned-id>
          # Timeout duration for requests made to the Azure Blob Storage account (in seconds)
          requestTimeout: <your-request-timeout>
          # Domain suffix of the Azure Blob Storage service endpoint (e.g., core.windows.net)
          endpointSuffix: <your-endpoint-suffix>
        bucketNames:
          chunks: "chunks"
          ruler: "ruler"
          admin: "admin"
    deploymentMode: SingleBinary
    singleBinary:
      resources:
        requests:
          cpu: 750m
          memory: 1500Mi
        limits:
          cpu: 2
          memory: 3Gi
      extraEnv:
        - name: GOMEMLIMIT
          value: 2700MiB
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
    chunksCache:
      # default is 500MB, with limited memory keep this smaller
      writebackSizeLimit: 10MB
    minio:
      enabled: true
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 512Mi
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    gateway:
      ingress:
        enabled: false
    # for logs drilldown
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
