apiVersion: v1
kind: ConfigMap
metadata:
  name: obot-default-privs-sql
data:
  default-privs.sql: |
    \set ON_ERROR_STOP 1
    -- variables: -v DB_NAME=... -v OWNER_ROLE=... -v APP_ROLE=...

    -- Create OWNER_ROLE if missing (works on any PG version)
    SELECT format('CREATE ROLE %I LOGIN;', :'OWNER_ROLE')
    WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'OWNER_ROLE') \gexec

    -- Create APP_ROLE (group role) if missing
    SELECT format('CREATE ROLE %I NOLOGIN;', :'APP_ROLE')
    WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'APP_ROLE') \gexec

    -- Allow Vault's DB user to GRANT the app role to others
    \set vm 'vault_manager'
    SELECT format('GRANT %I TO %I WITH ADMIN OPTION;', :'APP_ROLE', :'vm') \gexec

    -- Grant CONNECT to the app role on the database
    SELECT format('GRANT CONNECT ON DATABASE %I TO %I;', :'DB_NAME', :'APP_ROLE') \gexec

    -- Work in the target DB
    \connect :DB_NAME

    -- Ensure schema exists (schema name == DB_NAME)
    SELECT format('CREATE SCHEMA IF NOT EXISTS %I;', :'DB_NAME') \gexec

    -- USAGE on schema for the app role
    SELECT format('GRANT USAGE ON SCHEMA %I TO %I;', :'DB_NAME', :'APP_ROLE') \gexec

    -- Privileges on existing objects
    SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I;', :'DB_NAME', :'APP_ROLE') \gexec
    SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I;', :'DB_NAME', :'APP_ROLE') \gexec

    -- Default privileges for future objects created by OWNER_ROLE
    SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I;',
                  :'OWNER_ROLE', :'DB_NAME', :'APP_ROLE') \gexec
    SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO %I;',
                  :'OWNER_ROLE', :'DB_NAME', :'APP_ROLE') \gexec

    -- Set OWNER_ROLE search_path in this DB
    \connect postgres
    SELECT format('ALTER ROLE %I IN DATABASE %I SET search_path = %I, public;',
                  :'OWNER_ROLE', :'DB_NAME', :'DB_NAME') \gexec
