# Deploys longhorn
#
# - test with:
#   flux build kustomization longhorn-controller --path ./infrastructure/longhorn/controller --kustomization-file clusters/cluster03/latest/3-longhorn.yaml --dry-run
#   flux build kustomization longhorn-config --path ./infrastructure/longhorn/config --kustomization-file clusters/cluster03/latest/3-longhorn.yaml --dry-run
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-controller
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/longhorn/controller
  dependsOn:
    - name: tailscale-config
  # # test kustomization
  # components:
  #   - ../../../components/env-latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/longhorn/config
  dependsOn:
    - name: longhorn-controller
  # # test kustomization
  # components:
  #   - ../../../components/env-latest
