# Deploys longhorn
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-controller
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/longhorn/controller
  dependsOn:
    - name: vault-secrets-operator-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/longhorn/config
  dependsOn:
    - name: longhorn-controller
