# Deploys tailscale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-controller
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/tailscale/controller
  dependsOn:
    - name: vault-secrets-operator-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-config
  namespace: flux-system
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/tailscale/config
  dependsOn:
    - name: tailscale-controller
