# legacy-soh-3dbirth kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Prefix all resources with this name
namePrefix: legacy-soh-3dbirth-

# Replace base Namespace name and add all resources to this namespace
namespace: legacy-soh-3dbirth

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="legacy-soh-3dbirth"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:

  # Add TLS certificates for ingress
  - ../../components/ssl-certificates

  # Add Vault authentication (role and service accounts)
  - ../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../components/config-matcher
