# Deploys cloudnative-pg operator & postgresql cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-databases
  namespace: flux-system
  labels:
    environment: latest
spec:
  dependsOn:
    - name: cnpg-cluster

  interval: 24h
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/cloudnative-pg/app-databases
