# Deploys apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
  labels:
    environment: latest
spec:
  dependsOn:
    - name: infrastructure

  interval: 24h
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./infrastructure/cloudnative-pg/cnpg-operator