apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./scheduler-api
  - ./scheduler-web
  - namespace.yaml

# components:
  # Vault token to decrypt secrets
  # - ../../../components/sops-vault-token