apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: flux-

resources:
  - ./scheduler-api
  - ./scheduler-web

# components:
  # Vault token to decrypt secrets
  # - ../../../components/sops-vault-token