apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps
  # - ../../../infrastructure

labels:
- includeSelectors: true
  pairs:
    environment: latest

# Create a single resource for this environment that can be used by replacements.
#
configMapGenerator:
  - name: flux-env
    literals:
      - fluxEnv=latest
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:

  # Update image selection policy with a regex filter: {semverTag}-rc.{gitShortSha}+{timeStamp}
  #     eg. 2.4.10-rc.7731b9b1+1684912629
  - target:
      kind: ImagePolicy
    patch: |-
      - op: replace
        path: /spec/filterTags/pattern
        value: '^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)-.*$'
      # - op: replace
      #   path: /spec/policy
      #   value: {"semver": ">=1.0.0"}

  - target:
      kind: ImageRepository
    patch: |-
      - op: add
        path: /spec/exclusionList
        value: ["^review-.*$"]

    # patch: |-
    #   - op: add
    #     path: /spec/filterTags/extract
    #     value: '$timestamp'


  # Update oci repository ref selection to target all *.rc images
  #     eg. 2.4.10-rc.7731b9b1+1684912629
  - target:
      kind: OCIRepository
    patch: |-
      - op: replace
        path: /spec/ref
        value: {"semver": ">=1.0.0"}
