apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki

