---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring-crd
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-monitoring-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging-crd
  namespace: cattle-logging-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-logging-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
#---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: rancher-monitoring-crd
#   namespace: cattle-monitoring-system
# spec:
#   interval: 24h
#   install:
#     createNamespace: true
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#     crds: CreateReplace
#   chart:
#     spec:
#       chart: rancher-monitoring-crd
#       version: "108.0.0+up77.9.1-rancher.6"
#       sourceRef:
#         kind: HelmRepository
#         name: rancher-charts
#         namespace: flux-system
#   # values:
#   #   global:
#   #     cattle:
#   #       url: https://rancher3.ltc.bcit.ca
#   #       clusterId: c-7rtn4
#   #       clusterName: cluster01
#   #       systemProjectId: p-ktssc
#   #       rkePathPrefix: ""
#   #       rkeWindowsPathPrefix: ""
#   #       systemDefaultRegistry: ""
#   #       psp:
#   #         enabled: false
#   #     systemDefaultRegistry: ""
#   #   image:
#   #     repository: rancher/kuberlr-kubectl
#   #     tag: v6.0.0
#   #   nodeSelector: {}
#   #   tolerations: []
