---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  interval: 24h
  dependsOn:
    - name: rancher-logging-crd
      namespace: cattle-logging-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: rancher-logging
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  values:
    logging:
      enabled: false
    additionalLoggingSources:
      rke2:
        enabled: true
    systemdLogPath: /var/log/journal
    disablePvc: true
    fluentd:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
