# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-release.yaml
  - helm-repository.yaml
  - namespace.yaml

# Prefix all resources with this name
namePrefix: cnpg-

# Replace base Namespace name and add all resources to this namespace
namespace: cnpg-system

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="cloudnative-pg"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Source Chart Repo
  # url: https://cloudnative-pg.github.io/charts 

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

components:
  # Update resources based on ConfigMap above
  - ../../../components/config-matcher
