# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-release.yaml
  - helm-repository.yaml

# Prefix all resources with this name
# namePrefix: postgres-

configurations:
  - kustomizeconfig.yaml

# components:

  # Required for VaultAuth role and service accounts
  # - ../../../components/vault-auth
