apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: legacy-large-files
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  fsType: "ext4"
  # optional: staleReplicaTimeout: "30"  # minutes
