# Copy an app's `database-name` into various fields
# - https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: db-vars
      fieldPath: data.DB_NAME
    targets:

      # Replace the database name in Database resources
      - select:
          kind: Database
        fieldPaths:
          - spec.name
          - spec.schemas.*.name
          - spec.owner
          - spec.schemas.*.owner
        options:
          delimiter: "_"
          index: 0