---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: db-credentials
  annotations:
    app/db-host: pg-core-env-rw.postgres.svc.cluster.local
    app/db-port: "5432"
    app/db-name: db-name          # replaced by app overlays
spec:
  vaultAuthRef: vault-auth        # existing VSO auth in the app namespace
  mount: postgresql               # Vault DB engine mount path
  path: creds/role                # replaced by app overlays to creds/<app_role>

  destination:
    create: true
    name: db-credentials
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        # DATABASE_URL:
        #   text: |
        #     {{- $h := get .Annotations "app/db-host" -}}
        #     {{- $p := get .Annotations "app/db-port" -}}
        #     {{- $db := get .Annotations "app/db-name" -}}
        #     {{- printf "postgresql://%s:%s@%s:%s/%s?sslmode=prefer" (get .Secrets "username") (get .Secrets "password") $h $p $db -}}
        POSTGRES_HOST:     { text: "{{ get .Annotations \"app/db-host\" }}" }
        # PGPORT:     { text: "{{ get .Annotations \"app/db-port\" }}" }
        POSTGRES_DB: { text: "{{ get .Annotations \"app/db-name\" }}" }
        POSTGRES_USER:     { text: "{{ get .Secrets \"username\" }}" }
        POSTGRES_PASSWORD: { text: "{{ get .Secrets \"password\" }}" }
