# Watches helm chart repositories for new versions
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rancher-charts
spec:
  interval: 24h
  url: https://charts.rancher.io

