# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring-crd
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-monitoring-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 24h
  dependsOn:
    - name: rancher-monitoring-crd
      namespace: cattle-monitoring-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  chart:
    spec:
      chart: rancher-monitoring
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
  values:
    global:
      cattle:
        clusterId: c-7rtn4
        clusterName: cluster01
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.loki.svc.cluster.local:3100
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        size: 10Gi
        subPath: null
        type: pvc
        annotations: null
        finalizers: null
    prometheus:
      prometheusSpec:
        retention: 5d
        retentionSize: 25GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 25Gi
    nameOverride: rancher-monitoring
    namespaceOverride: cattle-monitoring-system
    rke2IngressNginx:
      enabled: true
    rke2ControllerManager:
      enabled: false
    rke2Scheduler:
      enabled: false
    rke2Proxy:
      enabled: false
    rke2Etcd:
      enabled: false
