# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-manager-secret
#   labels:
#     cnpg.io/reload: "true"
# type: kubernetes.io/basic-auth
# stringData:
#   username: vault_manager
#   password: "CHANGEME-SET-STRONG-PASSWORD"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-manager-secret
spec:
  type: kv-v2
  vaultAuthRef: postgres-vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure

  path: /postgres/vault-manager-secret
  destination:
    name: vault-manager-secret
    create: true
