# Configure a VaultAuth role and service account
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - vault-auth.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml
