# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: apps

  # path is prefixed by `{appName}/{environment}/`; double // required
  path: //admin-credentials
  destination:
    name: admin-credentials
    create: true
