apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring-crd
  namespace: cattle-monitoring-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rancher-monitoring-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 30m
  dependsOn:
    - name: rancher-monitoring-crd
      namespace: cattle-monitoring-system
  chart:
    spec:
      chart: rancher-monitoring
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    # Keep defaults; only add Loki datasource for Grafana
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          isDefault: false
          jsonData:
            timeout: 60
            maxLines: 2000
