apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging-crd
  namespace: cattle-logging-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-logging-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  interval: 30m
  dependsOn:
    - name: rancher-logging-crd
      namespace: cattle-logging-system
  chart:
    spec:
      chart: rancher-logging
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    # Minimal: rely on Rancher chart defaults (installs Logging operator + agents).
    # Add overrides only if your environment requires them.
    {}
