---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging-crd
  namespace: cattle-logging-system
spec:
  interval: 24h
  chart:
    spec:
      chart: rancher-logging-crd
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
