apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 30m
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: rancher-monitoring-crd
      namespace: cattle-monitoring-system
  chart:
    spec:
      chart: rancher-monitoring
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      version: "*"

  values:
    namespaceOverride: cattle-monitoring-system

    rke2IngressNginx:
      enabled: true
      namespaceOverride: kube-system
      service:
        selector:
          app.kubernetes.io/name: rke2-ingress-nginx

    prometheus:
      prometheusSpec:
        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
          requests:
            cpu: 750m
            memory: 750Mi
        retention: 8d
        retentionSize: 50GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: longhorn

    grafana:
      enabled: true

      persistence:
        enabled: true
        type: pvc
        size: 10Gi
        storageClassName: longhorn

      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          editable: true
          isDefault: false
          url: http://loki-gateway.loki.svc.cluster.local

      # Keep Rancher-style defaults for view access,
      # but allow admin login when using the Ingress URL.
      grafana.ini:
        auth:
          disable_login_form: false
        auth.anonymous:
          enabled: true
          org_role: Viewer
        auth.basic:
          enabled: true
        users:
          auto_assign_org_role: Viewer
        security:
          allow_embedding: true

      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana-monitoring.ltc.bcit.ca
        path: /
        tls: []
        # If you have a TLS secret already, uncomment this:
        # tls:
        #   - secretName: star-ltc-bcit-ca
        #     hosts:
        #       - grafana-monitoring.ltc.bcit.ca

