apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  install:
    createNamespace: true
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      reconcileStrategy: ChartVersion

  values:
    # --- RKE2 DNS defaults (fixes loki-gateway resolver) ---
    global:
      dnsService: rke2-coredns-rke2-coredns
      dnsNamespace: kube-system
      # Usually correct for RKE2; include explicitly to avoid cluster-domain surprises.
      clusterDomain: cluster.local

    deploymentMode: SingleBinary

    # Ensure we are NOT accidentally enabling the simple-scalable targets
    # (avoids "more than zero replicas for both singleBinary and simple scalable").
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    gateway:
      enabled: true

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1

      # Minimal TSDB-on-filesystem config that satisfies chart validation
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      storage:
        type: filesystem
        bucketNames:
          admin: admin
          chunks: chunks
          ruler: ruler

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

