apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  interval: 30m
  dependsOn:
    - name: rancher-logging-crd
      namespace: cattle-logging-system
  chart:
    spec:
      chart: rancher-logging
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    additionalLoggingSources:
      rke2:
        enabled: true

    # Turn PVC support ON (not mutually exclusive with Loki datasource)
    disablePvc: false

    # Keep operator lightweight
    resources: {}
    fluentbit:
      resources: {}
    fluentd:
      resources: {}

