---
apiVersion: v1
data:
  password: cU9lRzU5bHpqdGtSMWMwY0NLNEExV0RTNGJ3Y1FBZFg2
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: init-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-core

spec:
  instances: 3

  bootstrap:
    initdb:
      database: postgres
      owner: postgres

  storage:
    size: 10Gi

  postgresql:
    parameters:
      max_connections: "200"
      password_encryption: scram-sha-256    # Prefer modern hashing
      # log_statement: ddl

    pg_hba:
      # allow ingress-nginx (Pod CIDR) and in-cluster apps
      # - host  all  all  10.42.0.0/16  md5            # <-- replace with YOUR Pod CIDR
      # - host  all  all  127.0.0.1/32  md5
      # - host  all  all  ::1/128      md5
      # (Optionally) keep a broad rule during bring-up and remove later:
      - host  all  all  0.0.0.0/0   md5
      - host  all  all  ::0/0       md5

  enableSuperuserAccess: true
  superuserSecret:
    name: init-secret

  primaryUpdateStrategy: unsupervised

  resources:
    limits:
      cpu: "2"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "512Mi"

  # affinity:
  #   enablePodAntiAffinity: true
  #   topologyKey: failure-domain.beta.kubernetes.io/zone

  # backup:
  #   barmanObjectStore:
  #     data:
  #       compression: gzip
  #       encryption: AES256
  #       immediateCheckpoint: false
  #       jobs: 2

  #     destinationPath: s3://cluster-example-full-backup/

  #     endpointURL: http://custom-endpoint:1234

  #     s3Credentials:
  #       accessKeyId:
  #         key: ACCESS_KEY_ID
  #         name: backup-creds
  #       secretAccessKey:
  #         key: ACCESS_SECRET_KEY
  #         name: backup-creds

  #   retentionPolicy: "30d"
