---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-pg-core
spec:
  cluster:
    name: pg-core

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"