# Retrieves a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: star-latest-ltc-bcit-ca
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 24h
  mount: ltc-infrastructure
  path: vault/gh-private-oci-token
  destination:
    name: gh-private-oci-token
    create: true
