# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: gh-private-oci-token
spec:
  vaultAuthRef: vault-auth
  mount: github
  path: token
  params:
    org_name: "bcit-ltc"
  refreshAfter: 24h
  destination:
    create: true
    name: gh-private-oci-token
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        GITHUB_TOKEN:
          text: '{{ get .Secrets "token" }}'
