apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: github-private-repo-token
spec:
  vaultAuthRef: vault-auth
  mount: github
  path: token
  params:
    org_name: "bcit-ltc"
  refreshAfter: 24h
  destination:
    create: true
    name: github-private-repo-token
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludes:
        - .*
      templates:
        .dockerconfigjson:
          text: |
            {{- $token := get .Secrets "token" -}}
            {{- $user  := "x-access-token" -}}  {{/* username for GitHub App installation tokens */}}
            {{- $reg   := "ghcr.io" -}}
            {{- $auth  := printf "%s:%s" $user $token | b64enc -}}
            {{- dict "auths" (dict $reg (dict "username" $user "password" $token "auth" $auth)) | toJson -}}
