# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
spec:
  interval: 36h
  releaseName: cnpg-operator
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
      interval: 36h
  upgrade:
    crds: CreateReplace
