# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: star-web-ltc-bcit-ca
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: ssl-certificates/star-web-ltc-bcit-ca
  destination:
    name: star-web-ltc-bcit-ca
    create: true
    type: "kubernetes.io/tls"
