# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: ptracker-apis

  # path is prefixed by `{ptracker-apiName}/{environment}/`; double // required
  path: //postgres-credentials
  destination:
    name: postgres-credentials
    create: true
