---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: release-name
      fieldPath: data.releaseName
    targets:

      # Update the OCIRepository URL based on the name stored in the release's ConfigMap.
      - select:
          kind: OCIRepository
        fieldPaths:
          - spec.url
        options:
          delimiter: "/"
          index: 5

      # Update the HelmRelease chartRef to include a namespace based on the name stored in the release's ConfigMap.
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.releaseName
        options:
          create: true
