---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: app-name
      fieldPath: data.appName
    targets:

      # Update the GitRepository URL based on the app name (stored in app ConfigMap).
      - select:
          kind: GitRepository
        fieldPaths:
          - spec.url
        options:
          delimiter: "/"
          index: 6

      # Update the OCIRepository URL based on the app name (stored in app ConfigMap).
      - select:
          kind: OCIRepository
        fieldPaths:
          - spec.url
        options:
          delimiter: "/"
          index: 5

      # Update the ImageRepository image based on the app name (stored in app ConfigMap).
      - select:
          kind: ImageRepository
        fieldPaths:
          - spec.image
        options:
          delimiter: "/"
          index: 2

      # Update the HelmRelease chartRef to include a namespace based on the app name (stored in app ConfigMap).
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.chartRef.namespace
        options:
          create: true
