apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../../apps
  - ../../../infrastructure

labels:
- includeSelectors: true
  pairs:
    environment: stable

# Generate a re-usable environment variable for other resources
configMapGenerator:
  - name: flux-env
    literals:
      - fluxEnv="latest"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
