# Deploys apps
#
# - test "latest" with:
#   flux build kustomization apps --path ./apps --kustomization-file clusters/cluster03/latest/5-apps.yaml --dry-run
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
  annotations:
    fluxcd.io/workload: apps
spec:
  interval: 24h
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  dependsOn:
    - name: cloudnative-pg-config
  # # to test kustomization
  # components:
  #   - ../components/env-latest
