# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
spec:
  interval: 24h
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: helm-repository
      interval: 24h

  # This is one way to adjust default chart values
  values:
    hostname: "rancher3.ltc.bcit.ca"
    replicas: "-1"

    # Sets ingress secret to `tls-rancher-ingress`.
    # - see https://ranchermanager.docs.rancher.com/v2.10/getting-started/installation-and-upgrade/resources/add-tls-secrets
    ingress:
      tls:
        source: "secret"

    # Fixes agent CA configuration
    # - https://github.com/rancher/rancher/issues/45628#issuecomment-2246152604
    agentTLSMode: "system-store"
