# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
spec:
  interval: 24h
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: helm-repository
      interval: 24h
  values:
    hostname: "rancher3.ltc.bcit.ca"
    ingress:
      tls:
        source: "secret"
    replicas: "-1"
