apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Prefix all resources with this name
namePrefix: rancher-

# Replace base Namespace name and add all resources to this namespace
namespace: cattle-system

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="rancher"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/values
        value: {"values":{"hostname":"rancher2.ltc.bcit.ca","ingress":{"tls":{"source":"secret"}},"replicas":"-1"}}

# Source Chart Repo
  # url: https://releases.rancher.com/server-charts/stable
  - target:
      kind: OCIRepository
    patch: |-
      - op: replace
        path: /spec/verify/matchOIDCIdentity/0/subject
        value: "^https://github.com/bcit-ltc/oci/rancher.*$"

components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on ConfigMap above
  - ../../components/config-matcher

  # Required for VaultAuth role and serviceaccounts
  # - ../../components/generators/vault-auth
