apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: flux-

resources:
  - ./ptracker-api
  - ./ptracker-web
  - ./ptracker-guide

# components:
  # Vault token to decrypt secrets
  # - ../../../components/sops-vault-token