apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Prefix all resources with this name
namePrefix: infrastructure-documentation-

# Replace base Namespace name and add all resources to this namespace
namespace: infrastructure-documentation

# Generate an appName that is re-used as a variable for other resources
configMapGenerator:
  - name: app-name
    literals:
      - appName="infrastructure-documentation"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on the app-name stored in the ConfigMap
  - ../../components/config-matcher

  # Required for VaultAuth role and serviceaccounts
  # - ../../components/generators/vault-auth
