apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Prefix all resources with this name
namePrefix: infrastructure-documentation-

# Replace base Namespace name and add all resources to this namespace
namespace: infrastructure-documentation

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="infrastructure-documentation"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:
  - target:
      kind: OCIRepository
    patch: |-
      - op: replace
        path: /spec/verify/matchOIDCIdentity/0/subject
        value: "^https://github.com/bcit-ltc/oci/infrastructure-documentation.*$"

components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on ConfigMap above
  - ../../components/config-matcher

  # Required for VaultAuth role and serviceaccounts
  # - ../../components/generators/vault-auth
