---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - database.yaml
  - db-vars-configmap.yaml
  - default-privs-job.yaml
  - default-privs-sql-configmap.yaml

patches:
  - target:
      kind: Cluster
    patch: |-
      - op: add
        path: /spec/managed/roles/-
        value: { name: qcon_api_owner, login: true }
      - op: add
        path: /spec/managed/roles/-
        value: { name: qcon_api_app, login: false }
