---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: qcon-api
spec:
  cluster:
    name: pg-core
  name: qcon_api
  owner: app_shared
  schemas:
    - name: qcon_api
      owner: app_shared
