---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database
  namespace: postgres
spec:
  cluster:
    name: pg-core
  name: qcon_api
  owner: db_root_owner
  schemas:
    - name: qcon_api
      owner: db_root_owner
