---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: db-credentials
  annotations:
    # These annotations are used by the transformation below to compute DB env vars
    app/db-host: pg-core-env-rw.postgres.svc.cluster.local
    app/db-port: "5432"
    app/db-name: db-name          # replaced by app overlays
spec:
  vaultAuthRef: vault-auth        # existing VSO auth in the app namespace
  mount: postgresql               # patched by env overlays to postgresql-<env>
  path: creds/role                # patched by app overlays to creds/<app>-<env>

  destination:
    create: true
    name: db-credentials
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        POSTGRES_HOST:     { text: "{{ get .Annotations \"app/db-host\" }}" }
        POSTGRES_DB:       { text: "{{ get .Annotations \"app/db-name\" }}" }
        POSTGRES_USER:     { text: "{{ get .Secrets \"username\" }}" }
        POSTGRES_PASSWORD: { text: "{{ get .Secrets \"password\" }}" }
