agent_address = "/run/spire/agent/api.sock"

cert_dir = "/var/lib/spiffe/haproxy"
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "svid_bundle.pem"

cmd = "/usr/bin/sudo"
cmd_args = "-n /bin/systemctl reload haproxy"


renew_signal = ""
