# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 48h
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      # Set version here
      #   - caveat: requires patch
      #     `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag`
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 24h
  values:
    valuesFrom:
      - kind: ConfigMap
        name: values
