# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-azblob-credentials
spec:
  type: kv-v2
  vaultAuthRef: longhorn-azblob-vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: longhorn/azblob-credentials
  destination:
    name: longhorn-azblob-credentials
    create: true
