# Generates a secret from Vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-azblob-credentials
spec:
  type: kv-v2
  vaultAuthRef: longhorn-azblob-vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: longhorn/azblob-credentials
  destination:
    name: longhorn-azblob-credentials
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        "AZBLOB_ACCOUNT_NAME":
          text: "{{ .Secrets.storage_account_name }}"
        "AZBLOB_ACCOUNT_KEY":
          text: "{{ .Secrets.access_key }}"
