---
# Clones, updates, and commits new versions to app charts
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: image-automation
spec:
  interval: 48h
  sourceRef:
    kind: GitRepository
    name: git-repository
    commit:
      author:
        email: fluxcdbot@issues.ltc.bcit.ca
        name: fluxcdbot
      messageTemplate: |-
        Automated image update
                
        Changes:
        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}
        [skip ci]
    push:
      branch: main

    # For auto-PR's, see https://fluxcd.io/flux/use-cases/gh-actions-auto-pr/
    #      branch: staging
  update:
    strategy: Setters
  suspend: false
