---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database
spec:
  cluster:
    name: pg-core
  name: database
  owner: postgres         # Vault mints short-lived app users
  schemas:
    - name: schema
      owner: postgres
