---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: db-credentials
  annotations:
    app/db-host: pg-core.postgres.svc.cluster.local:5432
    app/db-name: db-name
spec:
  vaultAuthRef: vault-auth
  mount: postgres                           # Vault database engine mount
  path: credentials/role                    # Vault role that issues credentials for databases
  # rolloutRestartTargets:
  #   - kind: Deployment
  #     name: deployment
  destination:
    name: db-credentials                    # K8s Secret the app consumes
    create: true
    type: Opaque
    transformation:                         # build a DSN and expose common PG envs
      excludes: ["*"]
      templates:
        DATABASE_URL:
          text: |
            {{- $h := get .Annotations "app/db-host" -}}
            {{- $db := get .Annotations "app/db-name" -}}
            {{- printf "postgresql://%s:%s@%s/%s?sslmode=require" (get .Secrets "username") (get .Secrets "password") $h $db -}}
        PGHOST:      { text: "{{ get .Annotations \"app/db-host\" }}" }
        PGPORT:      { text: "{{ get .Annotations \"app/db-port\" }}" }
        PGDATABASE:  { text: "{{ get .Annotations \"app/db-name\" }}" }
        PGUSER:      { text: "{{ get .Secrets \"username\" }}" }
        PGPASSWORD:  { text: "{{ get .Secrets \"password\" }}" }
