# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database.yaml
  - dynamic-secret.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

