# corgi kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

# Prefix all resources with this name
namePrefix: corgi-

# Replace base Namespace name and add all resources to this namespace
namespace: corgi

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="corgi"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:

  # Add TLS certificates for ingress
  - ../../components/ssl-certificates

  # Add Vault authentication (role and service accounts)
  - ../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../components/config-matcher
