# Create a github webhook receiver
#   - path format is /hook/sha256sum(token+name+namespace)
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-webhook-receiver
spec:
  type: github
  interval: 48h
  events:
    - "ping"
    - "push"
  secretRef:
    name: github-webhook-token
  resources:
    # for flux-system resources
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: git-repository
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: kustomization
    # for app resources
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: oci-repository
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: helm-release
