# This file is for teaching kustomize how to substitute names
---
nameReference:

# Both GitRepository and Kustomization have a Receiver `spec.resources.name`
- kind: GitRepository
  fieldSpecs:
    - kind: Receiver
      path: spec/resources/name

- kind: Kustomization
  fieldSpecs:
    - kind: Receiver
      path: spec/resources/name
