# Create FluxCD notification providers, receivers, and alerts
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - github-webhook-receiver.yaml
  - github-webhook-token.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml
