agent {
  trust_domain = "${TRUST_DOMAIN}"

  data_dir = "/var/lib/spire/agent"
  log_level = "INFO"

  server_address = "${SERVER_ADDRESS}"
  server_port = 8081

  trust_bundle_path = "/etc/spire.d/bootstrap.bundle"

  socket_path = "/run/spire/agent/api.sock"
}

plugins {
  NodeAttestor "x509pop" {
    plugin_data {
      private_key_path  = "/etc/spire.d/x509pop.key"
      certificate_path  = "/etc/spire.d/x509pop.crt"
    }
  }
  WorkloadAttestor "unix" { }
  KeyManager "disk" { plugin_data { directory = "/var/lib/spire/agent" } }
}
