apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../base
  - headlamp.yaml

# Prefix all resources with this name
namePrefix: headlamp-

# Replace base Namespace name and add all resources to this namespace
namespace: kube-system

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="headlamp"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Source Chart Repo
  # url: https://kubernetes-sigs.github.io/headlamp/

# patches:
#   - target:
#       kind: HelmRelease
#     patch: |-
#       - op: add
#         path: /spec/values
#         value: {"values":{"hostname":"headlamp2.ltc.bcit.ca","ingress":{"tls":{"source":"secret"}},"replicas":"-1"}}

components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on ConfigMap above
  - ../../components/config-matcher

  # Required for VaultAuth role and service accounts
  # - ../../components/generators/vault-auth
